import Head from 'next/head'
import MainNavbar from '../components/MainNavbar'
import QuickNavbar from '../components/QuickNavbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Alberton Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainNavbar />
        <QuickNavbar />
      </main>

      <footer>
      </footer>
    </>
  )
}
